cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name="cart"),
    path('add_cart/<int:product_id>', views.add_cart, name='add_cart'),
    path('remove_cart/<int:id>', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:cart_id>',
         views.remove_cart_item, name='remove_cart_item'),
    path('checkout', views.checkout, name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include("store.urls")),
    path('cart/', include("cart.urls")),
    path('account/', include("accounts.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('<int:category_id>', views.store, name='products_by_category'),
    path('<int:category_id>', views.store, name='products_by_category'),
    path('<int:category_id>/<int:product_id>',
         views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from accounts.models import Account
from store.models import Product, VariationProduct

# Create your models here.


class Cart(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE, null=True,
                                related_name='cart')
    cart_id = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

    def get_total_item(self):
        return sum(map(lambda x: x.quantity, self.cart_items.all()))

    def get_total_price(self):
        return sum(map(lambda x: x.quantity * x.product.price, self.cart_items.all()))


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(
        VariationProduct, related_name="variations")
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name='cart_items')
    quantity = models.IntegerField(default=0)
    is_activate = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse
# Create your models here.


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to="photos/products")
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail', args=[self.category.id, self.id])

    def is_out_of_stock(self):
        return self.stock <= 0


class VariationType:
    SIZE = 0
    COLOR = 1
    VARIANT_CHOICES = (
        (SIZE, 'size'),
        (COLOR, 'color'),
    )


class VariationProduct(models.Model):
    from store.managers.variation_product import VariationProductManager

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='variations')
    variation_type = models.IntegerField(
        default=0, choices=VariationType.VARIANT_CHOICES)
    variation_value = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = VariationProductManager()

    def __str__(self):
        return self.variation_value

cart/views.py
from statistics import variance
from django.shortcuts import get_object_or_404, render, redirect
from cart.models import Cart, CartItem
from cart.service.cart import CartService
from store.managers.variation_product import VariationProductQuerySet
from store.models import Product, VariationProduct, VariationType
from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.


def cart(request):
    cart = CartService.get_cart(request)
    if cart is not None:
        cart_items = cart.cart_items.all()
        total_item = cart.get_total_item()
        total_price = cart.get_total_price()
    else:
        cart_items = []
        total_item = 0
        total_price = 0
    context = {
        'cart_items': cart_items,
        'total_item': total_item,
        'total_price': total_price,
    }

    return render(request, 'store/cart.html', context)


def add_cart(request, product_id):
    data = request.POST.copy()
    color = data.get('color')
    size = data.get('size')
    product = Product.objects.get(id=product_id)
    _filter = Q(variation_type=VariationType.COLOR, variation_value=color) | Q(
        variation_type=VariationType.SIZE, variation_value=size)
    variations = VariationProduct.objects.filter(_filter, product=product)
    cart = CartService.get_cart(request) or CartService.create_cart(request)
    cart_items = CartItem.objects.filter(
        product=product, cart=cart, variations=variations.first())
    item = CartItem.objects.none()
    for cart_item in cart_items:
        if set(cart_item.variations.all()) == set(variations):
            item = cart_item
            break
    if not item:
        item = CartItem.objects.create(product=product, cart=cart)
        item.variations.add(*variations)
    item.quantity += 1
    item.save()
    _update_product_stock(product, -1)
    return redirect('cart')


def remove_cart(request, id):
    cart = CartService.get_cart(request)
    try:
        cart_item = CartItem.objects.get(id=id, cart=cart)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
        _update_product_stock(cart_item.product, 1)
    except cart_item.DoesNotExist:
        pass
    return redirect('cart')


def remove_cart_item(request, cart_id):
    try:
        cart_item = CartItem.objects.get(id=cart_id)
        cart_item.delete()
        _update_product_stock(cart_item.product, cart_item.quantity)
    except cart_item.DoesNotExist:
        pass
    return redirect('cart')


@login_required(login_url='login')
def checkout(request):
    try:
        cart = CartService.get_cart(request)
        cart_items = cart_items = cart.cart_items.all()
        total_item = cart.get_total_item()
        total_price = cart.get_total_price()
    except Cart.DoesNotExist:
        cart_items = []
        total_item = 0
        total_price = 0
    context = {
        'cart_items': cart_items,
        'total_item': total_item,
        'total_price': total_price,
    }
    return render(request, 'store/checkout.html', context)


def _update_product_stock(product: Product, quantity: int) -> Product:
    product.stock += quantity
    product.save()
    return product

store/views.py
from turtle import end_fill
from django.shortcuts import render, get_object_or_404, get_list_or_404

from category.models import Category
from .models import Product, VariationProduct
from django.core.paginator import Paginator
# Create your views here.


def store(request, category_id=None):
    search_keyword = request.GET.get('search_keyword')
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        products = Product.objects.filter(category=category, is_available=True)
    else:
        products = Product.objects.all().filter(is_available=True)
    if search_keyword:
        products = products.filter(product_name__icontains=search_keyword)
    product_count = products.count()
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 6)
    products = paginator.get_page(page)
    context = {
        'products': products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_id=None, product_id=None):
    product = get_object_or_404(
        Product, id=product_id, category_id=category_id)
    product_sizes = product.variations.only_sizes()
    product_colors = product.variations.only_colors()
    context = {'product': product,
               'product_sizes': product_sizes, 'product_colors': product_colors}
    return render(request, 'store/product_detail.html', context)
"#dbc785"

templates/store/cart.html
{% extends 'base.html' %} {% load static%} {% block content %}
<section class="section-content padding-y bg">
	<div class="container">
		<!-- ============================ COMPONENT 1 ================================= -->
		{% if not cart_items %}
		<h2 class="text-center">Your Cart Is Empty</h2>
		<div class="text-center">
			<a href="{% url 'store'%}" class="text-center btn btn-primary">
				Continue Shopping
			</a>
		</div>
		{% else %}
		<div class="row">
			<aside class="col-lg-9">
				<div class="card">
					<table class="table table-borderless table-shopping-cart">
						<thead class="text-muted">
							<tr class="small text-uppercase">
								<th scope="col">Product</th>
								<th scope="col" width="120">Quantity</th>
								<th scope="col" width="120">Price</th>
								<th
									scope="col"
									class="text-right"
									width="200"
								></th>
							</tr>
						</thead>
						<tbody>
							{% for item in cart_items %}
							<tr>
								<td>
									<figure class="itemside align-items-center">
										<div class="aside">
											<img
												src="{{ item.product.images.url }}"
												class="img-sm"
											/>
										</div>
										<figcaption class="info">
											<a
												href="{{ item.product.get_url}}"
												class="title text-dark"
												>{{item.product.product_name}}</a
											>
											<p class="text-muted small">
												{% for variation in item.variations.all %}
												{{variation.get_variation_type_display}}: {{variation.variation_value}}
												<br />
												{% endfor %}
											</p>
										</figcaption>
									</figure>
								</td>
								<td>
									<!-- col.// -->
									<div class="col">
										<div class="input-group input-spinner">
											<div class="input-group-prepend">
												<form action="{% url 'remove_cart' item.id %}" method="POST">
													{% csrf_token %}
													<button
														class="btn btn-light"
														type="submit"
														id="button-plus"
													>
														<i class="fa fa-minus"></i>
													</button>
												</form>
											</div>
											<input
												type="text"
												class="form-control"
												value="{{ item.quantity}}"
											/>
											<div class="input-group-append"></div>
												<form action="{% url 'add_cart' item.product.id %}" method="POST">
													{% csrf_token %}
													{% for variation in item.variations.all %}
													<input
														type="hidden"
														name="{{variation.get_variation_type_display}}"
														value="{{variation.variation_value}}"
													/>
													{% endfor %}
													<button
														class="btn btn-light"
														type="submit"
														id="button-plus"
													>
														<i class="fa fa-plus"></i>
													</button>
												</form>
											</div>
										</div>
										<!-- input-group.// -->
									</div>
									<!-- col.// -->
								</td>
								<td>
									<div class="price-wrap">
										<var class="price"
											>${{ item.sub_total}}</var
										>
										<small class="text-muted">
											${{ item.product.price}} each
										</small>
									</div>
									<!-- price-wrap .// -->
								</td>
								<td class="text-right">
									<a
										href="{% url 'remove_cart_item' item.id %}"
										class="btn btn-danger"
									>
										Remove</a
									>
								</td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
			<aside class="col-lg-3">
				<div class="card">
					<div class="card-body">
						<dl class="dlist-align">
							<dt>Total price:</dt>
							<dd class="text-right">${{ total_price }}</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Tax:</dt>
							<dd class="text-right">$0.00</dd>
						</dl>
						<dl class="dlist-align">
							<dt>Total:</dt>
							<dd class="text-right text-dark b">
								<strong>${{ total_price }}</strong>
							</dd>
						</dl>
						<hr />
						<p class="text-center mb-3">
							<img
								src="{% static 'images/misc/payments.png' %}"
								height="26"
							/>
						</p>
						<a
							href="{% url 'checkout' %}"
							class="btn btn-primary btn-block"
						>
							Checkout
						</a>
						<a
							href="{% url 'store'%}"
							class="btn btn-light btn-block"
							>Continue Shopping</a
						>
					</div>
					<!-- card-body.// -->
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
		</div>
		<!-- row.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->
		{% endif %}
	</div>
	<!-- container .//  -->
</section>
{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %} {% load static%} {% block content %}
<section class="section-content padding-y bg">
	<div class="container">
		<!-- ============================ COMPONENT 1 ================================= -->
		<div class="row">
			<aside class="col-lg-6">
                <div class="cart">
                    <div class="cart-body">
                        <h4 class="card-title mb-4">Billing Address</h4>
                        <form action="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">First Name</label>
                                    <input type="text" name="firstname" class="form-control"  placeholder="First Name">
                                </div>
                                <div class="col form-group">
                                    <label for="">Last Name</label>
                                    <input type="text" name="lastname" class="form-control"  placeholder="Last Name">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Email</label>
                                    <input type="email" name="email" class="form-control"  placeholder="Email">
                                </div>
                                <div class="col form-group">
                                    <label for="">Phone Number</label>
                                    <input type="text" name="phone_number" class="form-control"  placeholder="Phone Number">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Address Line 1</label>
                                    <input type="text" name="address" class="form-control"  placeholder="Address Line">
                                </div>
                                <div class="col form-group">
                                    <label for="">Address Line 2</label>
                                    <input type="text" name="address2" class="form-control"  placeholder="Address Line 2">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">City</label>
                                    <input type="text" name="city" class="form-control"  placeholder="City">
                                </div>
                                <div class="col form-group">
                                    <label for="">State</label>
                                    <input type="text" name="state" class="form-control"  placeholder="State">
                                </div>
                                <div class="col form-group">
                                    <label for="">Country</label>
                                    <input type="text" name="country" class="form-control"  placeholder="Country">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Order Note</label>
                                    <textarea type="text" name="address" class="form-control" rows="2" placeholder="Order Note"></textarea>
                                </div>
                            </div>
                    </div>
                </div>
				
			</aside>
			<!-- col.// -->
			<aside class="col-lg-6">
                
				<div class="card">
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside">
                                            <img
                                                src="{{ item.product.images.url }}"
                                                class="img-sm"
                                            />
                                        </div>
                                        <figcaption class="info">
                                            <a
                                                href="{{ item.product.get_url}}"
                                                class="title text-dark"
                                                >{{item.product.product_name}}</a
                                            >
                                            <p class="text-muted small">
                                                {% for variation in item.variations.all %}
                                                {{variation.get_variation_type_display}}: {{variation.variation_value}}
                                                <br />
                                                {% endfor %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <label for="">{{item.quantity}}</label>
                                </td>
                                <td>
                                    <div class="price-wrap">
                                        <var class="price"
                                            >${{ item.sub_total}}</var
                                        >
                                        <small class="text-muted">
                                            ${{ item.product.price}} each
                                        </small>
                                    </div>
                                    <!-- price-wrap .// -->
                                </td>
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
					<div class="card-body">
						<button
                            type="submit"
							href="./place-order.html"
							class="btn btn-primary btn-block"
						>
							Place Order
						</button>
						<a
							href="{% url 'store'%}"
							class="btn btn-light btn-block"
							>Continue Shopping</a
						>
					</div>
                </form>
					<!-- card-body.// -->
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
		</div>
		<!-- row.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->
	</div>
	<!-- container .//  -->
</section>
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="section-content padding-y bg">
	<div class="container">
		<!-- ============================ COMPONENT 1 ================================= -->
		<div class="card">
			<div class="row no-gutters">
				<aside class="col-md-6">
					<article class="gallery-wrap">
						<div class="img-big-wrap">
							<a href="#"
								><img src="{{ product.images.url}}"
							/></a>
						</div>
						<!-- img-big-wrap.// -->
					</article>
					<!-- gallery-wrap .end// -->
				</aside>
				<main class="col-md-6 border-left">
					<form
						action="{% url 'add_cart' product.id %} "
						method="post"
					>
						{% csrf_token %}
						<article class="content-body">
							<h2 class="title">{{ product.product_name}}</h2>

							<div class="mb-3">
								<var class="price h4">${{ product.price }}</var>
							</div>

							<p>{{ product.description }}</p>

							<p>In stock: {{ product.stock }}</p>

							<hr />
							<div class="row">
								<div class="item-option-select">
									<h6>Choose Color</h6>
									<div
										class="btn-group btn-group-sm btn-group-toggle"
										data-toggle="buttons"
									>
										{% for color in product_colors %}
										<label class="btn btn-light">
											<input
												type="radio"
												name="color"
												value="{{color.variation_value}}"
											/>
											{{color.variation_value}}
										</label>
										{% endfor %}
									</div>
								</div>
							</div>
							<!-- row.// -->
							<div class="row">
								<div class="item-option-select">
									<h6>Select Size</h6>
									<div
										class="btn-group btn-group-sm btn-group-toggle"
										data-toggle="buttons"
									>
										{% for size in product_sizes %}
										<label class="btn btn-light">
											<input
												type="radio"
												name="size"
												value="{{size.variation_value}}"
											/>
											{{size.variation_value}}
										</label>
										{% endfor %}
									</div>
								</div>
							</div>
							<!-- row.// -->
							<hr />
							{% if not product.is_out_of_stock %}
							<button type="submit" class="btn btn-primary">
								<span class="text">Add to cart</span>
								<i class="fas fa-shopping-cart"></i>
							</button>
							{% else %}
							<h2 class="text-danger">Out of stock</h2>
							{% endif %}
						</article>
					</form>
					<!-- product-info-aside .// -->
				</main>
				<!-- col.// -->
			</div>
			<!-- row.// -->
		</div>
		<!-- card.// -->
		<!-- ============================ COMPONENT 1 END .// ================================= -->

		<br />

		<div class="row">
			<div class="col-md-9">
				<header class="section-heading">
					<h3>Customer Reviews</h3>
				</header>

				<article class="box mb-3">
					<div class="icontext w-100">
						<img
							src="{% static './images/avatars/avatar1.jpg' %}"
							class="img-xs icon rounded-circle"
						/>
						<div class="text">
							<span class="date text-muted float-md-right"
								>24.04.2020
							</span>
							<h6 class="mb-1">Mike John</h6>
						</div>
					</div>
					<!-- icontext.// -->
					<div class="mt-3">
						<p>
							Dummy comment Lorem ipsum dolor sit amet,
							consectetur adipisicing elit, sed do eiusmod tempor
							incididunt ut labore et dolore magna aliqua. Ut enim
							ad minim veniam, quis nostrud exercitation ullamco
							laboris nisi ut aliquip
						</p>
					</div>
				</article>
			</div>
			<!-- col.// -->
		</div>
		<!-- row.// -->
	</div>
	<!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/store.html
{% extends 'base.html' %} {% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
	<div class="container">
		<h2 class="title-page">Our Store</h2>
	</div>
	<!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
	<div class="container">
		<div class="row">
			<aside class="col-md-3">
				<div class="card">
					<article class="filter-group">
						<header class="card-header">
							<a
								href="#"
								data-toggle="collapse"
								data-target="#collapse_1"
								aria-expanded="true"
								class=""
							>
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Categories</h6>
							</a>
						</header>
						<div
							class="filter-content collapse show"
							id="collapse_1"
							style=""
						>
							<div class="card-body">
								<ul class="list-menu">
									<li>
										<a href="{% url 'store' %}"
											>All products</a
										>
									</li>
									{% for category in links %}
									<li>
										<a href="{{ category.get_url }}"
											>{{ category.category_name}}</a
										>
									</li>
									{% endfor %}
								</ul>
							</div>
							<!-- card-body.// -->
						</div>
					</article>
					<!-- filter-group  .// -->
					<article class="filter-group">
						<header class="card-header">
							<a
								href="#"
								data-toggle="collapse"
								data-target="#collapse_4"
								aria-expanded="true"
								class=""
							>
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Sizes</h6>
							</a>
						</header>
						<div
							class="filter-content collapse show"
							id="collapse_4"
							style=""
						>
							<div class="card-body">
								<label class="checkbox-btn">
									<input type="checkbox" />
									<span class="btn btn-light"> XS </span>
								</label>

								<label class="checkbox-btn">
									<input type="checkbox" />
									<span class="btn btn-light"> SM </span>
								</label>

								<label class="checkbox-btn">
									<input type="checkbox" />
									<span class="btn btn-light"> LG </span>
								</label>

								<label class="checkbox-btn">
									<input type="checkbox" />
									<span class="btn btn-light"> XXL </span>
								</label>
							</div>
							<!-- card-body.// -->
						</div>
					</article>
					<!-- filter-group .// -->

					<article class="filter-group">
						<header class="card-header">
							<a
								href="#"
								data-toggle="collapse"
								data-target="#collapse_3"
								aria-expanded="true"
								class=""
							>
								<i class="icon-control fa fa-chevron-down"></i>
								<h6 class="title">Price range</h6>
							</a>
						</header>
						<div
							class="filter-content collapse show"
							id="collapse_3"
							style=""
						>
							<div class="card-body">
								<div class="form-row">
									<div class="form-group col-md-6">
										<label>Min</label>
										<!-- <input class="form-control" placeholder="$0" type="number"> -->
										<select class="mr-2 form-control">
											<option value="0">$0</option>
											<option value="50">$50</option>
											<option value="100">$100</option>
											<option value="150">$150</option>
											<option value="200">$200</option>
											<option value="500">$500</option>
											<option value="1000">$1000</option>
										</select>
									</div>
									<div class="form-group text-right col-md-6">
										<label>Max</label>
										<select class="mr-2 form-control">
											<option value="50">$50</option>
											<option value="100">$100</option>
											<option value="150">$150</option>
											<option value="200">$200</option>
											<option value="500">$500</option>
											<option value="1000">$1000</option>
											<option value="2000">$2000+</option>
										</select>
									</div>
								</div>
								<!-- form-row.// -->
								<button class="btn btn-block btn-primary">
									Apply
								</button>
							</div>
							<!-- card-body.// -->
						</div>
					</article>
					<!-- filter-group .// -->
				</div>
				<!-- card.// -->
			</aside>
			<!-- col.// -->
			<main class="col-md-9">
				<header class="border-bottom mb-4 pb-3">
					<div class="form-inline">
						<span class="mr-md-auto"
							><b>{{ product_count }}</b> Items found
						</span>
					</div>
				</header>
				<!-- sect-heading -->
				<div class="row">
					{% for item in products %}
					<div class="col-md-4">
						<figure class="card card-product-grid">
							<div class="img-wrap">
								<a href="{{ item.get_url }}" class="title"
									><img src="{{ item.images.url }}"
								/></a>
							</div>
							<!-- img-wrap.// -->
							<figcaption class="info-wrap">
								<div class="fix-height">
									<a href="{{ item.get_url}}" class="title"
										>{{ item.product_name }}</a
									>
									<div class="price-wrap mt-2">
										<span class="price"
											>{{ item.price }}</span
										>
									</div>
									<!-- price-wrap.// -->
								</div>
								<a
									href="{% url 'add_cart' item.id%}"
									class="btn btn-block btn-primary"
									>Added to cart
								</a>
							</figcaption>
						</figure>
					</div>
					<!-- col.// -->
					{% endfor %}
				</div>
				<!-- row end.// -->

				<nav class="mt-4" aria-label="Page navigation sample">
					{% if products.has_other_pages %}
					<ul class="pagination">
						{% if products.has_previous %}
						<li class="page-item">
							<a
								class="page-link"
								href="?page={{ products.previous_page_number}}"
								>Previous</a
							>
						</li>
						{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">Previous</a>
						</li>
						{% endif %} 
						{% for index in products.paginator.page_range %} 
							{% if index == products.number %}
							<li class="page-item active">
								<a class="page-link" href="?page={{index}}"
									>{{index}}</a
								>
							</li>
							{% else %}
							<li class="page-item">
								<a class="page-link" href="?page={{index}}"
									>{{index}}</a
								>
							</li>
							{% endif %} 
						{% endfor %} 
						
						{% if products.has_next %}
						<li class="page-item">
							<a
								class="page-link"
								href="?page{{ products.next_page_number}}"
								>Next</a
							>
						</li>
						{% endif%}
					</ul>
					{% endif %}
				</nav>
			</main>
			<!-- col.// -->
		</div>
	</div>
	<!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}